acbn/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blogs')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls', namespace='users')),
 
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path("",views.home,name='home'),
    path("about",views.AboutView.as_view(),name='about'),
    path("contact",views.ContactView.as_view(),name='contact'),
    path('devis/', views.devis, name='devis'),
    path('blog/',views.PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', views.CreatePostView.as_view(), name='create_post'),
    path('blog/<int:id>/delete_post/', views.delete_post, name='delete_post'),
    path('blog/<int:id>/delete_partner/', views.delete_partner, name='delete_partner'),
    path('blog/<int:id>/delete_doc/', views.delete_doc, name='delete_doc'),
    path('blog/update_post/<int:pk>', views.UpdatePostView.as_view(), name='update_post'),
    path('blog/update_partner/<int:pk>', views.UpdatePartnerView.as_view(), name='update_partner'),
    path('blog/update_doc/<int:pk>', views.UpdateDocView.as_view(), name='update_doc'),
    path('blog/add_categorie/', views.AddCategorieView.as_view(), name='add_categorie'),
    path('blog/add_doc/', views.AddDocsView.as_view(), name='add_doc'),
    path('blog/add_partner/', views.AddPartnerView.as_view(), name='add_partner'),
    path('blog/categorie/<str:cats>/', views.sameCategorieList, name='same_categorie_list'),
    path('activite/', views.activiteListView, name='activite'),
    path('etudes_au_niger/', views.etudesListView, name='etudes'),
    path('partnaires/', views.PartnerListView.as_view(), name='partners'),
    path('documents/', views.DocsListView.as_view(), name='documents'),
    path('blog/categorie_list/', views.categorieListView, name='categorie_list'),
    path('blog/like/<int:pk>', views.like_view, name='like_view'),
    path('blog/<int:pk>/add_comment/',views.AddCommentView.as_view(), name ='add_comment_section'),
    path('blog/<int:pk>/author_profile', views.showProfileView.as_view(), name='showProfileView')
    


]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from PIL import Image
import cloudinary

from cloudinary.models import CloudinaryField
# Create your models here.

cloudinary.config( 
  secure=True,
  cloud_name = 'CLOUD_NAME', 
  api_key = 'API_KEY', 
  api_secret = 'API_SECRET' 
)
class Categorie(models.Model):
     name = models.CharField(max_length=255)

     def __str__(self):
        return self.name
    

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    #text = models.TextField()
    text = RichTextField(blank=True, null=True)
    post_image = CloudinaryField('image',default='media/blog.jpg')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now= True)
    categorie =models.ForeignKey(Categorie, on_delete = models.CASCADE, null=True, blank = True)
    likes = models.ManyToManyField(User, related_name ='blog_posts')
    snippet = models.CharField(max_length=255, default='Lire')

    def get_absolute_url(self):
        return reverse("blogs:post_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)


class Partner(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = CloudinaryField('image',default='media/blog.jpg')
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now= True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blogs:partners")

class Documents(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = RichTextField(blank=True, null=True)
    doc_file = models.FileField(upload_to='files/', blank=True,null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now= True)    

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blogs:documents")
    

blog/forms.py
from django import forms
from blog.models import Post, Categorie,Comment,Documents,Partner

class PostForm(forms.ModelForm):

    class Meta:
        model= Post
        fields = ['title','text','post_image','categorie','snippet']
        widgets = {
            'title': forms.TextInput(attrs={"class":'form-control' ,'name':'title'}),
        'text' : forms.Textarea(attrs={'class':"form-control", 'name':"text", 'cols':"30" ,'rows':"10" }),
        'snippet' : forms.Textarea(attrs={'class':"form-control", 'name':"snippet", 'cols':"30" ,'rows':"5" }),
        'categorie' : forms.Select(attrs={'class':"form-control", 'name':"categorie" }),
        'pos_image' : forms.FileInput(attrs={'class':"form-control", 'name':"image" }),
        } 

class PartnerForm(forms.ModelForm):

    class Meta:
        model= Partner
        fields = ['name','image']
        widgets = {
            'name': forms.TextInput(attrs={"class":'form-control' ,'name':'nom'}),
            'image' : forms.FileInput(attrs={'class':"form-control", 'name':"image" }),
        } 

class DocForm(forms.ModelForm):

    class Meta:
        model= Documents
        fields = ['title','description','doc_file']
        widgets = {
            'title': forms.TextInput(attrs={"class":'form-control' ,'name':'title'}),
            'description' : forms.Textarea(attrs={'class':"form-control", 'name':"description", 'cols':"30" ,'rows':"10" }),
            'doc_file' : forms.FileInput(attrs={'class':"form-control", 'name':"fichier" }),
        } 
class AddCommentForm(forms.ModelForm):

    class Meta:
        model= Comment
        fields = ['name','text']
        widgets = {
            'name': forms.TextInput(attrs={"class":'form-control' ,'name':'name'}),
        'text' : forms.Textarea(attrs={'class':"form-control", 'name':"text", 'cols':"30" ,'rows':"10" }),
        
        } 

class AddCategorieForm(forms.ModelForm):

    class Meta:
        model= Categorie
        fields = ['name',]
        widgets = {
            'name': forms.TextInput(attrs={"class":'form-control' ,'name':'name'}),
            
        
        
        } 

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post, Categorie, Comment,Partner,Documents
from django.utils import timezone
from blog.forms import PostForm,AddCommentForm,AddCategorieForm,PartnerForm,DocForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy,reverse
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView )
from django.contrib import messages
from django.http import HttpResponseRedirect
from users.models import Profile


# Create your views here.

    
    
def home(request):
    categories = Categorie.objects.all()[:6]
    posts = Post.objects.order_by('-created_date')[:3]
    context = {'categories':categories,
                'posts':posts }
    return render(request,'home.html',context)

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html' 

def devis(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        email_content = request.POST.get('email_content')
       
        message = email_content
        send_mail(
            'ACBN <no_reply>',
            'Cher '+' '+ name + 'nous avons recu votre message, nous vous donnerons une suite tres bientot.',
            'yvindjhonnelmahoukou@gmail.com',
            [email],
            fail_silently=False,
        )
        send_mail(
            'Requete du site de ACBN',
            message,
            'yvindjhonnelmahoukou@gmail.com',
            ['yvindjhonnelmahoukou@gmail.com'],
            fail_silently=False,
        )
        messages.info(request, f'La demande a été envoyée avec succès, vous serez averti par email.')
        return redirect('services:home')

    else:
        return render(request,'home.html')
      
class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post_list.html'
    ordering = ['-created_date']

    def get_context_data(self,*args,**kwargs):
        categorie_menu = Categorie.objects.all()
        context=super(PostListView,self).get_context_data(*args,**kwargs) 
        context['categorie_menu'] = categorie_menu 
        return context 


class PartnerListView(ListView):
    model = Partner
    context_object_name = 'partners'
    template_name = 'blog/partners.html'
    ordering = ['-created_date']

class DocsListView(ListView):
    model = Documents
    context_object_name = 'documents'
    template_name = 'blog/documents.html'
    ordering = ['-created_date']


def activiteListView(request):
    categorie = Categorie.objects.get(name='activite')
    posts = Post.objects.filter(categorie=categorie)
    context = {
                'posts':posts }
    return render(request,'blog/activite.html',context)

       

def etudesListView(request):
    categorie = Categorie.objects.get(name='etude')
    posts = Post.objects.filter(categorie=categorie)
    context = {
                'posts':posts }
       
    return render(request,'blog/etudes.html',context)

class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_detail.html'
    
    def get_context_data(self,*args,**kwargs):
        categorie_menu = Categorie.objects.all()
        context=super(PostDetailView,self).get_context_data(*args,**kwargs) 
        stuff = get_object_or_404(Post, id= self.kwargs['pk'])
        total_likes = stuff.total_likes() 
        Liked = False
        if stuff.likes.filter(id = self.request.user.id).exists():
            Liked =True
        context['categorie_menu'] = categorie_menu
        context['total_likes'] = total_likes
        context['Liked'] = Liked
        return context 


class CreatePostView(CreateView):
    model = Post
    template_name = 'blog/create_post.html'
    form_class = PostForm
    

    def form_valid(self,form):
        
        form.instance.author = self.request.user
        
        return super().form_valid(form)

class AddDocsView(CreateView):
    model = Documents
    template_name = 'blog/create_post.html'
    form_class = DocForm
    

    def form_valid(self,form):
        
        form.instance.author = self.request.user
        
        return super().form_valid(form)

class AddPartnerView(CreateView):
    model = Partner
    template_name = 'blog/create_post.html'
    form_class = PartnerForm
    

    def form_valid(self,form):
        
        form.instance.author = self.request.user
        
        return super().form_valid(form)
            
def delete_post(request, id):
    Post(id = id).delete()
    messages.success(request, f'suppression reuissie.')
    return redirect('blogs:post_list')

def delete_doc(request, id):
    Documents(id = id).delete()
    messages.success(request, f'suppression reuissie.')
    return redirect('blogs:documents')

def delete_partner(request, id):
    Partner(id = id).delete()
    messages.success(request, f'suppression reuissie.')
    return redirect('blogs:partners')

class UpdatePostView(UpdateView):
    model = Post
    template_name= 'blog/update_post.html'
    form_class = PostForm

class UpdateDocView(UpdateView):
    model = Documents
    template_name= 'blog/update_doc.html'
    form_class = DocForm

class UpdatePartnerView(UpdateView):
    model = Partner
    template_name= 'blog/update_doc.html'
    form_class = PartnerForm


class AddCategorieView(CreateView):

    model = Categorie
    template_name = 'blog/add_categorie.html'
    #form_class = AddCategorieForm
    fields = '__all__'
    success_url = reverse_lazy('blogs:create_post')


class AddCommentView(CreateView):

    model = Comment
    template_name = 'blog/add_comment_section.html'
    form_class = AddCommentForm
    #fields = '__all__'
    success_url = reverse_lazy('blogs:post_list')

    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

def sameCategorieList(request, cats):
    categorie = get_object_or_404(Categorie, name = cats)
    categorie_posts = categorie.post_set.all()
    context = {'cats':cats.title().replace('-',' '), 
               'categorie_posts':categorie_posts,
               }

    return render(request,'blog/same_categorie_list.html', context)
    
def categorieListView(request):
     categorie_list_view = Categorie.objects.all()
     return render(request,'blog/categorie_list.html', {'categorie_list_view':categorie_list_view}) 

def like_view(request, pk):
    post = get_object_or_404(Post, id = request.POST.get('post_id'))
    Liked = False
    if post.likes.filter(id = request.user.id).exists() :
        post.likes.remove(request.user.id)
        Liked = False
    else :
         post.likes.add(request.user)
         Liked = True
    return HttpResponseRedirect(reverse('blogs:post_detail', args = str(pk)))
    

class showProfileView(DetailView):
    model = Profile
    template_name ='blog/showProfileView.html'

    def get_context_data(self,*args,**kwargs):
        
        user_page = get_object_or_404(Profile, id= self.kwargs['pk'])
        context = super(showProfileView,self).get_context_data(*args,**kwargs)
        context['user_page'] = user_page
        return context

blog/templates/blog/activite.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->

<section id="overviews" class="section wb">

  <div class="container">
    
     {% if request.user.is_authenticated and request.user.profile.is_teacher == True %}
     
    <a href="{% url 'blogs:create_post' %}"><button type="button" class="btn btn-info">Ajouter une Activité</button></a>
      {% endif %} 
    <br/><br/>
       <!--blog post-->
       <div class="row">
    {% if posts %}
  
        {% for post in posts %}
       
       
          <div class="col-lg-4 blog-post"> 
       
         
            {% if post.post_image %}
            <img src="{{post.post_image.url }}" style="height: 200px; width: 350px;"/>
            {% endif %}
          <h3>{{ post.title }}</h3>
          <p>{{ post.text|truncatewords:30|capfirst|safe }}</p>
       
          
          <a href="{% url 'blogs:post_detail' post.id %}" class="btn btn-primary">Lire</a>
         {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
          {% if user.id == post.author.id %}
          <a href="{% url 'blogs:update_post' post.id %}" class="btn btn-info">Mettre à jour</a>
          {% endif %}
          {% endif %}
          {% endif %}
       
        </div>
        {% endfor %}
        {% else %} 

<p>Aucune Activité, désolé!!!</p>
        {% endif %}
    
     
  
      </div>
      

    </div>

</section>
<!-- Page end -->

{% endblock content %}

blog/templates/blog/add_categorie.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1>Créer une nouvelle catégorie</h1>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="site-btn">Valider</button>
    </form>

</div>
<br>
{% endblock %}

blog/templates/blog/categorie_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

       <!--blog categories list-->
       <h1>blog categories</h1>
       {% if categorie_list_view %}
             {% for item in categorie_list_view %}
             
                 
            <h4> <a  href="{% url 'blogs:same_categorie_list' item %}">
						
                {{ item }}
            </a>  </h4>    
     
             {% endfor %}
        
        
        {% else %} 

<p>Aucun post, désolé!!!</p>
        {% endif %}
    
     
  
      </div>
      

    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="text-center">
{% if request.user.is_authenticated %}
    {% if request.user.profile.is_teacher == True %}
        <h1>Créer un post</h1>
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
        <!--   <label for="">Title*</label>
            <input type="text" class="form-control" name="title" placeholder="Titre de l'article...">
            <label for="">Article*</label>
            <textarea class="form-control" name="text" id="" cols="30" rows="10" placeholder="Publier un contenu..."></textarea>
            <label for="Categorie">Categorie*</label>
            <select class="form-control" >
                {% if choice_list%}
                {% for categorie in choice_list %}
            <option value= cat ="categorie_{{categorie}}">{{ categorie }}</option>
                {% endfor %}
                {% endif %}
            </select>
            <label for="">Snippet*</label>
            <textarea class="form-control" name="snippet" id="" cols="30" rows="5""></textarea> 
            <br/>
             -->
           
            <button class="site-btn">Créer le message</button>
           
        </form>

    <br>
    
    <a href="{% url 'blogs:add_categorie' %}"><button class="site-btn" class="site-btn">Créer une nouvelle catégorie</button></a>
    
    <br/>
  
  
{% endif %}
  
{% endif %}           
        
{% endblock %}

blog/templates/blog/documents.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->

<section id="overviews" class="section wb">
 
    
  <div class="container">
    {% if request.user.is_authenticated and request.user.profile.is_teacher == True %}
     
    <a href="{% url 'blogs:add_doc' %}"><button type="button" class="btn btn-info">Ajouter un document</button></a>
      {% endif %} 
    <br/><br/>
    <div class="row ">
       <!--blog post-->
     {% if documents %}
  
     {% for post in documents %}
      <div class="col-lg-4 blog-post">
    
      
          <h3><a href="{{ post.doc_file.url }}">{{ post.title }}</a></h3>
          <br><a href="{{ post.doc_file.url }}" download>Telecharger</a>     ||  <strong> <a href="#">Lire</a></strong>
       
          
        
         {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
          {% if user.id == post.author.id %}
          <a href="{% url 'blogs:update_doc' post.id %}" class="btn btn-info">Mettre à jour</a>
          {% endif %}
          {% endif %}
          {% endif %}
    </div>
        
     
        {% endfor %}

        {% else %} 

<p>Aucun document, désolé!!!</p>
        {% endif %}
     </div>
     
  
      </div>
      

  

</section>
<!-- Page end -->

{% endblock content %}

blog/templates/blog/partners.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->

<section id="overviews" class="section wb">

  <div class="container">
   
     {% if request.user.is_authenticated and request.user.profile.is_teacher == True %}
     
    <a href="{% url 'blogs:add_partner' %}"><button type="button" class="btn btn-info">Ajouter un partenaire</button></a>
      {% endif %} 
    <br/><br/>
       <!--blog post-->
       <div class="row">
       
    {% if partners %}
  
        {% for post in partners %}
        <div class="col-lg-4 blog-post">
      
          {% if post.image %}
          <img src="{{ post.image.url }}" alt="mon_image" class="img-fluid">
          {% endif %}
          <h3>{{ post.name }}</h3>
         
          
         
         {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
          {% if user.id == post.author.id %}
          <a href="{% url 'blogs:update_partner' post.id %}" class="btn btn-info">Mettre à jour</a>
          <a href="{% url 'blogs:delete_partner' post.id %}" class="btn btn-info">Supprimer</a>
          {% endif %}
          {% endif %}
          {% endif %}
        </div>
        {% endfor %}
        {% else %} 

<p>Aucun post, désolé!!!</p>
        {% endif %}
    
     
  
      </div>
      

    </div>

</section>
<!-- Page end -->

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<section id="overviews" class="section wb">
<div class="container">
    <div class="row">
      <div class="col">
          <h1>Détails du message:</h1>
        <!-- blog post -->
        <div class="blog-post">
          
          <img src="{{ post.post_image.url }}" alt="mon_image" class="img-fluid">
       
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#admin">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
            </div>
          </div>
          <p>{{ post.text|capfirst|safe }} </p>
          <a href="{% url 'blogs:post_list' %}" class="btn btn-success">Liste des Articles</a>
          {% if post.author == request.user %}
          <a href="{% url 'blogs:delete_post' post.id %}" class="btn btn-danger">Supprimer le message</a>
          <a href="{% url 'blogs:update_post' post.id %}" class="btn btn-info">Mettre à jour</a>
          {% endif %}
        <br>

<hr>

<form action="{% url 'blogs:like_view' post.pk %}" method="POST">
  {% csrf_token %}
  {% if Liked %}
  <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-danger btn-sm">Unlike</button> 

{% else %}

  <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-primary btn-sm">Like</button> - {{ total_likes }} Likes
</form>

{% endif %}
<br>
<hr>
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-2">
      <img src="{{ post.author.profile.profile_pic.url }}" class="card-img">
    </div>
<div class="col-md-10">
  <div class="card-body">
    <h5 class="card-title" id="admin">{{ post.author|capfirst }}</h5>
    <p class="small text-muted">
      <a href="{% url 'blogs:showProfileView' post.author.profile.pk %}">Profile |</a>
      {% if post.author.profile.website_url %}
        <a href="{{post.author.profile.website_url }}">Website</a> | 
        {% endif %}
        {% if post.author.profile.facebook_url %} <a href="{{post.author.profile.facebook_url }}">Facebook</a> |
        {% endif %}
        {% if post.author.profile.instagram_url %}<a href="{{post.author.profile.instagram_url }}">Instagram</a> | {% endif %}
        {% if post.author.profile.twitter_url %}<a href="{{post.author.profile.twitter_url }}">Twitter</a> |{% endif %}
        {% if post.author.profile.linkedin_url %}<a href="{{post.author.profile.linkedin_url }}"> LinkedIn</a> {% endif %}</p>
    <p class="card-text">{{post.author.profile.bio }}</p>
   
    


</div>

</div>
</div>
</div>
<hr>
<h2> Commentaires </h2>
{% if not post.comments.all %}
Aucun commentaire... <a href="{% url 'blogs:add_comment_section' post.id %}">Ajouter un commentaire</a>
{% else %}
<a href="{% url 'blogs:add_comment_section' post.id %}">Ajouter un commentaire </a>
<br> <br>
{% for comment in post.comments.all %}
<strong>{{ comment.name }}-
  {{ comment.date_added }}</strong>
  <br/>
  {{ comment.text }}
  <br><br>
 {% endfor %} 
 <a href="{% url 'blogs:add_comment_section' post.id %}">Ajouter un commentaire </a>
 {% endif %}
 
<br> <br>
 <hr>
</div>
</div>



</div>
</div>
</section>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->

<section id="overviews" class="section wb">

  <div class="container">
   
     {% if request.user.is_authenticated and request.user.profile.is_teacher == True %}
     
    <a href="{% url 'blogs:create_post' %}"><button type="button" class="btn btn-info">Créer un Article</button></a>
      {% endif %} 
    <br/><br/>
       <!--blog post-->
       <div class="row">
       
    {% if posts %}
  
        {% for post in posts %}
      
        <div class="col-lg-4 blog-post"> 
         
          <img src="{{ post.post_image.url }}" alt="mon_image" class="img-fluid">
          
          <h3>{{ post.title }}</h3>
          <p>{{ post.text|truncatewords:30|capfirst|safe }}</p>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            
            <div>
              <strong>Categorie :</strong>  <a href="{% url 'blogs:same_categorie_list' post.categorie %}">{{ post.categorie }}</a>
          </div>
        </div>
        <a href="{% url 'blogs:post_detail' post.id %} " class="btn btn-primary">{{ post.snippet|safe }}</a>
          
         
         {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
          {% if user.id == post.author.id %}
          <a href="{% url 'blogs:update_post' post.id %}" class="btn btn-info">Mettre à jour</a>
          {% endif %}
          {% endif %}
          {% endif %}
        </div>
        {% endfor %}
        {% else %} 

<p>Aucun post, désolé!!!</p>
        {% endif %}
    
     
  
      </div>
      

    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

blog/templates/blog/same_categorie_list.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->
<section class="blog-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-9">
     

       <!--blog categories post-->
      
       <h1>Catégorie : {{ cats }}</h1> 
       {% if categorie_posts %}
     {% for post in categorie_posts %}
  
      
    <div class="blog-post">
      <img src="{{ post.post_image.url }}" alt="mon_image" height="200" width="400">
      <h3>{{ post.title }}</h3>
      <div class="blog-metas">
        <div class="blog-meta author">
          <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
          <a href="#">{{ post.author|capfirst }}</a>
        </div>
        <div class="blog-meta">
          <a href="#">{{ post.created_date }}</a>
          
        </div>
        <div>
          <strong>Categorie :</strong>  <a href="{% url 'blogs:same_categorie_list' post.categorie|slugify %}">{{ post.categorie }}</a>
      </div>
    </div>
      <p>{{ post.text|capfirst|truncatewords:100|safe }} </p>
      <a href="{% url 'blogs:post_detail' post.id %}" class="btn btn-primary">Read More</a>
      {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
      {% if user.id == post.author.id %}
      <a href="{% url 'blogs:update_post' post.id %}" class="btn btn-info">Mettre à jour</a>
      {% endif %}
      {% endif %}
      {% endif %}
    </div>
    
   {% endfor %}
   {% else %}
   <p>Aucun post, désolé!!!</p>
       {% endif %}

       
    
  
      </div>
      

    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}