acbn/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace='blogs')),
    path('accounts/',include('allauth.urls')),
    path('users/',include('users.urls', namespace='users')),
 
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path("",views.home,name='home'),
    path("about",views.AboutView.as_view(),name='about'),
    path("contact",views.ContactView.as_view(),name='contact'),
    path('devis/', views.devis, name='devis'),
    path('blog/',views.PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', views.CreatePostView.as_view(), name='create_post'),
    path('blog/<int:id>/delete_post/', views.delete_post, name='delete_post'),
    path('blog/<int:id>/delete_partner/', views.delete_partner, name='delete_partner'),
    path('blog/<int:id>/delete_doc/', views.delete_doc, name='delete_doc'),
    path('blog/update_post/<int:pk>', views.UpdatePostView.as_view(), name='update_post'),
    path('blog/update_partner/<int:pk>', views.UpdatePartnerView.as_view(), name='update_partner'),
    path('blog/update_doc/<int:pk>', views.UpdateDocView.as_view(), name='update_doc'),
    path('blog/add_categorie/', views.AddCategorieView.as_view(), name='add_categorie'),
    path('blog/add_doc/', views.AddDocsView.as_view(), name='add_doc'),
    path('blog/add_partner/', views.AddPartnerView.as_view(), name='add_partner'),
    path('blog/categorie/<str:cats>/', views.sameCategorieList, name='same_categorie_list'),
    path('activite/', views.activiteListView, name='activite'),
    path('etudes_au_niger/', views.etudesListView, name='etudes'),
    path('partnaires/', views.PartnerListView.as_view(), name='partners'),
    path('documents/', views.DocsListView.as_view(), name='documents'),
    path('blog/categorie_list/', views.categorieListView, name='categorie_list'),
    path('blog/like/<int:pk>', views.like_view, name='like_view'),
    path('blog/<int:pk>/add_comment/',views.AddCommentView.as_view(), name ='add_comment_section'),
    path('blog/<int:pk>/author_profile', views.showProfileView.as_view(), name='showProfileView')
    


]

users/urls.py
from django.urls import path

from .views import Profile

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),

  

]

templates/about.html
{% extends "base.html" %}
{% load static %}

{% load i18n %}
{% block content %}
<div id="overviews" class="section wb">
    <div class="container">
        <div class="section-title row text-center">
            <div class="col-md-8 offset-md-2">
                <h3>Genèse</h3>
                <p class="lead"> Nous sommes une plateforme de préparation d'examen et concours, Nous accompagnons et orientons les élèves et étudiants tout au long de leur cursus accadémique. Notre siège social se trouve  à Brazzaville, République du Congo.</p>
            </div>
        </div><!-- end title -->
    
        <div class="row align-items-center">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="message-box">
                    <h4>2020 Lancement de la plateforme Schooli par l'exploit Lothar</h4>
                    <h2>Bienvenu à SchooliEducation</h2>
                    <p>Vous y trouverez  les épreuves des examens et concours corrigés et de nombreux sujets et exercices de prépartion pour les différents concours et examens, Nous sommes disponible dans plusieurs pays d'afrique, notament dans toute l'Afrique centrale</p>

                    <p> Nous vous aidons à reuissir votre parcours accadémique. </p>

                    <a href="#" class="hover-btn-new orange"><span>Lire</span></a>
                    
                </div><!-- end messagebox -->
            </div><!-- end col -->
            
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="post-media wow fadeIn">
                    <img src="{% static 'schooli/images/about_02.jpg' %}" alt="" class="img-fluid img-rounded">
                </div><!-- end media -->
            </div><!-- end col -->
        </div>
        <div class="row align-items-center">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="post-media wow fadeIn">
                    <img src="{% static 'schooli/images/about_03.jpg' %}" alt="" class="img-fluid img-rounded">
                </div><!-- end media -->
            </div><!-- end col -->
            
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="message-box">
                    <h2>Regoignez nous dans nos Centres de formations.</h2>
                    <p>Nous disposant des centres de formations à Brazzaville et à pointe-Noire, deux villes de la république du Congo. Nous disposons aussi des cours en ligne.</p>

                    <p> Vous pouvez passer des tests en ligne sur notre plateforme pour jauger votre niveau dans le rythme qui vous convient..</p>

                    <a href="#" class="hover-btn-new orange"><span>Learn More</span></a>
                </div><!-- end messagebox -->
            </div><!-- end col -->
            
        </div><!-- end row -->
    </div><!-- end container -->
</div><!-- end section -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">   
   
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
 
     <!-- Site Metas -->
    <title>ACBN</title>  
    <meta name="keywords" content="ACBN">
    <meta name="description" content="Association des Congolais de Brazzaville au Niger">
    <meta name="author" content="ACBN">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'schooli/css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'schooli/css/style.css' %}">
    <!-- ALL VERSION CSS -->
    <link rel="stylesheet" href="{% static 'schooli/css/versions.css ' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'schooli/css/responsive.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'schooli/css/custom.css' %}">

    <!-- Modernizer for Portfolio -->
    <script src="{% static 'schooli/js/modernizer.js' %}"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="host_version"> 

	<!-- Modal -->
	

    <!-- LOADER -->
    <!-- <div id="preloader">
		<div class="loader-container">
			<div class="progress-br float shadow">
				<div class="progress__item"></div>
			</div>
		</div>
	</div> -->
	
	<!-- END LOADER -->	
			
	<!-- Start header -->
 <div class="container-fluid" >
  <div class="row social_style" style="width: 100%; margin: auto;">
    <div class="col-12 col-md-4">

      <ul class="social-icons" >
        <li><a  href="#" target="_blank" ><i class="fa fa-envelope"></i>bloufouma@gmail.com</a></li>
       
       
    
      </ul></div>
      <div class="col-6 col-md-4">

        <ul class="social-icons">
        
          <li ><a  href="#" target="_blank"><i class="fa fa-phone"></i>+1 434 422 207 5</a></li>
         
      
        </ul></div>
      <div class="col-6 col-md-4"  >
      <ul class="social-icons"  >
        <li><a  href="#" target="_blank" style="padding-right:10px;"><i class="fa fa-facebook"></i></a></li>
        <li><a  href="#" target="_blank" style="padding-right:10px;"><i class="fa fa-instagram"></i></a></li>
        <li><a  href="#" target="_blank" style="padding-right:10px;"><i class="fa fa-linkedin"></i></a></li>
        <li><a  href="#" target="_blank" style="padding-right:10px;"><i class="fa fa-twitter"></i></a></li>
        <li><a  href="#" target="_blank" style="padding-right:10px;"><i class="fa fa-rss"></i></a></li>
       
    
      </ul>
      </div>
    </div>
    <div class="row" >    
  <header class="top-navbar" style="width: 100%; margin: auto;">
	
     
     
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="{%url 'blogs:home'%}">
          <img src="{% static 'schooli/images/logo.jpg' %}" alt="ACBN" />
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-host" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            
          </button>
              
          <div class="collapse navbar-collapse" id="navbars-host">
            <ul class="navbar-nav ml-auto">
            
          
          
      
            <li 
            {% if '/' == request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
         
                <a class="nav-link" href="{%url 'blogs:home'%}">Acceuil</a>
            </li>
            <li 
            {% if 'about' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{%url 'blogs:about'%}">Présentation</a>
            </li>
            <li 
            {% if 'activite' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{%url 'blogs:activite'%}">Activités</a>
            </li>
            <li 
            {% if 'documents' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{% url 'blogs:documents' %}">Documents</a>
            </li>
            <li 
            {% if 'partners' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{% url 'blogs:partners' %}">partenaires</a>
            </li> 
            <li  {% if 'etudes' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{% url 'blogs:etudes' %}">Etudier au Niger</a>
            </li>
            <li {% if 'contact' in request.path %}
            class="nav-item active"
            {% else %}
            class="nav-item"
            {% endif %}>
              <a class="nav-link" href="{% url 'blogs:contact' %}">Contacts</a>
            </li>
  
           
              
              </ul>
  
              <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
          <li class="nav-item dropdown">
            
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{request.user.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdown-a">
            <a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'account_logout' %}">Sortie</a>
            </div>
          
          </li>
          {% else %}
        
                          <li class="nav-item  dropdown">
                          <a class="nav-link dropdown-toggle" href="#" role="button"  data-toggle="dropdown"   aria-haspopup="true" aria-expanded="false"><span class="fa fa-user"></span> Mon compte </a>
                          <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                                             
                                      <a class="dropdown-item" href="{% url 'account_login' %}" >
                                          <span class="fa fa-user icon-min-width-20"></span>Connexion
                                      </a>
                                  
                                  
                                      <a  class="dropdown-item" href="{% url 'account_signup' %}">
                                          <span class="fa fa-user-plus icon-min-width-20"></span>Inscription
                                      </a>
                                                
                          </div>
                                                            
                      </li>
  
            {% endif %}
          </ul>
    
        </nav>
      </header>
      </div>
    
    
             
  <!-- End header -->
   


<!-- messages alerts -->

{% include 'inc/messages.html' %}

  {% block content %}
  
  {% endblock %}

</div>	                    
<footer >
  <div class="copyrights">
      <div class="container-fluid">
          <div class="footer-distributed">
              <div class="footer-center">                   
                  <p class="footer-company-name">All Rights Reserved. &copy; 2020 <a href="#">acbn.assoc <a href="https://acbnassoc.herokuapp.com/">exploit lothar</a></p>
              </div>
          </divactivite>
      </div><!-- end container -->
</div><!-- end copyrights -->

</footer>




    <a href="#" id="scroll-to-top" class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>
 
    <!-- ALL JS FILES -->
    <script src="{% static 'schooli/js/all.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'schooli/js/custom.js' %}"></script>
	<script src="{% static 'schooli/js/timeline.min.js' %}"></script>
	<script>
		timeline(document.querySelectorAll('.timeline'), {
			forceVerticalMode: 700,
			mode: 'horizontal',
			verticalStartPosition: 'left',
			visibleItems: 4
		});
	</script>
			
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <!-- Page Content -->
    
<section id="overviews" class="section wb">

  <div class="container">
    <div class="row">
          <div class="col-md-12">
            <h1>CONTACTS</h1>
            <span>Nous contacter maintenant</span>
          </div>
        </div>
      </div>
  

    <div class="contact-information">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-phone"></i>
              <h4>Phone</h4>
              <p>Nous sommes disponibles 24/24.</p>
              <a href="#">+1 434 422 207 5</a>
            


            </div>
          </div>
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-envelope"></i>
              <h4>Email</h4>
              <p>Evrivez nous par mail.</p>
              <a href="#">bloufouma@gmail.com</a>
            </div>
          </div>
          <div class="col-md-4">
            <div class="contact-item">
              <i class="fa fa-map-marker"></i>
              <h4>Adresse</h4>
              <p>08 Rue<br>Issa Beri,Niamey Niger</p>
              <a href="#">Notre localisation Google Maps</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include 'devis.html' %}




</section> 
    
{% endblock %}

templates/devis.html
<div class="callback-form">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section-heading">
            <h2>Envoyez nous votre  <em>devis</em></h2>
            <span>Exprimer votre besoin et nous donnerons suite à votre réquête</span>
          </div>
                </div>
                <div class="col-md-12">
                  <div class="contact-form">
                    <form id="contact" action="{% url 'blogs:devis' %}" method="post">
                      {% csrf_token  %}
                      <div class="row">
                        <div class="col-lg-4 col-md-12 col-sm-12">
                          <fieldset>
                            <input name="name" type="text" class="form-control" id="name" placeholder="Full Name" required="">
                          </fieldset>
                        </div>
                        <div class="col-lg-4 col-md-12 col-sm-12">
                          <fieldset>
                            <input name="email" type="text" class="form-control" id="email" pattern="[^ @]*@[^ @]*" placeholder="E-Mail Address" required="">
                          </fieldset>
                        </div>
                       
                       

                         

                        <div class="col-lg-12">
                            <fieldset>
                              <textarea name="email_content" rows="6" class="form-control" id="message" placeholder="Your Message" required=""></textarea>
                            </fieldset>
                          </div>
                        <div class="col-lg-12">
                          <fieldset>
                            <button type="submit" id="form-submit" class="filled-button">Envoyez</button>
                          </fieldset>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>

templates/etudes.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page  -->

<section id="overviews" class="section wb">

  <div class="container">
    <div class="row">
      <div class="col-lg-9">
     {% if request.user.is_authenticated and request.user.profile.is_teacher == True %}
     
    <a href="{% url 'blogs:create_post' %}"><button type="button" class="btn btn-info">Créer un post sur les études</button></a>
      {% endif %} 
    <br/><br/>
       <!--blog post-->
    {% if posts %}
  
        {% for post in posts %}
      
        <div class="blog-post">
         
          <img src="{{ post.post_image.url }}" alt="mon_image" class="img-fluid">
          
          <h3>{{ post.title }}</h3>
          <div class="blog-metas">
            <div class="blog-meta author">
              <div class="post-author set-bg" data-setbg="/media/{{ post.author.profile.profile_pic }}"></div>
              <a href="#">{{ post.author|capfirst }}</a>
            </div>
            <div class="blog-meta">
              <a href="#">{{ post.created_date }}</a>
              
            </div>
            <div>
              <strong>Categorie :</strong>  <a href="{% url 'blogs:same_categorie_list' post.categorie %}">{{ post.categorie }}</a>
          </div>
        </div>
        <p>{{ post.snippet|safe }} </p>
          
          <a href="{% url 'blogs:post_detail' post.id %}" class="btn btn-primary">Read More</a>
         {% if request.user.is_authenticated %}
         {% if request.user.profile.is_teacher == True %}
          {% if user.id == post.author.id %}
          <a href="{% url 'blogs:update_post' post.id %}" class="btn btn-info">Mettre à jour</a>
          {% endif %}
          {% endif %}
          {% endif %}
        </div>
        {% endfor %}
        {% else %} 

<p>Aucun post, désolé!!!</p>
        {% endif %}
    
     
  
      </div>
      

    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/history.html
{% load static %}
<section class="section lb page-section">
    <div class="container">
         <div class="section-title row text-center">
            <div class="col-md-8 offset-md-2">
                <h3>Notre Histoire</h3>
                <p class="lead">Schoolieducation a été créée par Exploit Lothar, un jeune congolais. Les premières lignes de code de Schooli ont été codées dans le campus de L'EAMAC, à niamey, au Niger.</p>
            </div>
        </div><!-- end title -->
        <div class="timeline">
            <div class="timeline__wrap">
                <div class="timeline__items">
                    <div class="timeline__item">
                        <div class="timeline__content img-bg-01">
                            <h2>2020</h2>
                            <p>Naissance de SchooliEducation, précisement en Octobre 2020. la prémière version de Schooli à été mis en ligne sur la plateforme Heroku le samédi 24 Octobre 2020 par Exploit Lothar.</p>
                        </div>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
</section>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}


<div id="overviews" class="section wb">
    <div class="container">
       
     <div class="row">
         <div class="col">
            <div id="carouselExampleControls" class="carousel slide bs-slider box-slider" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                  <li data-target="#carouselExampleControls" data-slide-to="0" class="active"></li>
                  <li data-target="#carouselExampleControls" data-slide-to="1"></li>
                  <li data-target="#carouselExampleControls" data-slide-to="2"></li>
                </ol>
              
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% if posts %}
                    {% for post in posts %}
        
                  <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
                    <img src="{{ post.post_image.url }}" class=" w-100" alt="">
                    <div class="carousel-caption first-ly" >
                      <h2 >{{ post.title }}</h2>
                      <a href="{% url 'blogs:post_detail' post.id %}"><p class="btn btn-info">{{post.snippet|truncatewords:5}} </p></a>
                    </div>
                  </div>
              
                 
                  {% endfor %}
                  {% endif %}
                </div>
              
                <!-- Left and right controls -->
                <a class="left carousel-control-prev" href="#carouselExampleControls" data-slide="prev">
                  <span class="fa fa-angle-left"></span>
                  <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control-next" href="#carouselExampleControls" data-slide="next">
                  <span class="fa fa-angle-right"></span>
                  <span class="sr-only">Next</span>
                </a>
              </div>
         
     </div>             
     </div>
    </div><!-- end container -->
</div><!-- end section -->
     <div id="overviews" class="section wb">
        <div class="container">
        <div class="row align-items-center" id="about">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="message-box">
                   
                    <h2>A PROPOS DE NOUS</h2>
                    <p>Bienvenue sur le site des Congolais du Niger!
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                    </p>
                    <p>Bienvenue sur le site des Congolais du Niger!
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                        lorem ipsim hdgf shuks ddi sgsu, sksuze. sgsj 
                     
                    </p>

                 

                    <a href="{%url 'blogs:about'%}" class="hover-btn-new orange"><span>Lire</span></a>
                </div><!-- end messagebox -->
            </div><!-- end col -->
            
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="post-media wow fadeIn">
                    <img src="{% static 'schooli/images/acbn1.jpg' %}" alt="" class="img-fluid img-rounded">
                </div><!-- end media -->
            </div><!-- end col -->
        </div> <!-- end row -->
        <div class="row align-items-center">
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="post-media wow fadeIn">
                    <img src="{% static 'schooli/images/acbn2.jpg' %}" alt="" class="img-fluid img-rounded">
                </div><!-- end media -->
            </div><!-- end col -->
            
            <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                <div class="message-box">
                    <h2>REGOIGNEZ NOUS DANS NOS ACTIVITES</h2>
                    <p>Lorem ipsum lorem ipsum lorel ndshsk Lorem ipsum lorem ipsum lorel ndshsk Lorem ipsum lorem ipsum lorel ndshsk Lorem ipsum lorem ipsum lorel ndshsk 
                        Lorem ipsum lorem ipsum lorel ndshsk 
                    </p>

                    <p> Lorem ipsum lorem ipsum lorel ndshsk Lorem ipsum lorem ipsum lorel ndshsk Lorem ipsum lorem ipsum lorel ndshsk .</p>
                    <a href="{%url 'blogs:activite'%}" class="hover-btn-new orange"><span>Lire</span></a>
                </div><!-- end messagebox -->
            </div><!-- end col -->
            
        </div><!-- end row -->
  
    </div><!-- end container -->
</div><!-- end section -->
{% endblock %}